NAME = Phone_Directory

TEST_NAME = Test_$(NAME)

BUILD = Build

SRC = src/Create_record.c\
src/Delete_record.c\
src/Listing_record.c\
src/Modify_record.c\
src/Search_record.c\
src/Clear.c\
src/Test_address.c\
src/Test_Country_Code.c\
src/Test_Mobile.c\
src/Test_name.c\
src/Test_sex.c\

TEST_SRC = ${SRC}\
Test/Test_Phone_Directory.c\
unity/unity.c\

INC = -Iinc\
-Iunity

#To check if the OS is Windows or Linux and set the executable file extension and delete command accordingly
ifdef OS
   RM = del /q
   FixPath = $(subst /,\,$1)
   EXEC = exe
else
   ifeq ($(shell uname), Linux)
      RM = rm -rf
      FixPath = $1
	  EXEC = out
   endif
endif

# Makefile will not run target command if the name with file already exists. To override, use .PHONY
.PHONY : all test coverage run clean doc

all : $(BUILD)
	gcc Start.c $(SRC) $(INC) -o $(call FixPath,$(BUILD)/$(NAME).$(EXEC))

run : all
	$(call FixPath,$(BUILD)/$(NAME).$(EXEC))

test : $(SRC) $(TEST_SRC)
	gcc $^ $(INC) -o $(call FixPath,$(BUILD)/$(TEST_NAME).$(EXEC))
	$(call FixPath,$(BUILD)/$(TEST_NAME).$(EXEC))

coverage : ${PROJECT_NAME}
	gcc -fprofile-arcs -ftest-coverage $(SRC) $(TEST_SRC) $(INC) -o $(call FixPath,$(BUILD)/$(TEST_NAME).$(EXEC))
	$(call FixPath,$(BUILD)/$(TEST_NAME).$(EXEC))
	gcov -a $(SRC)

doc:
	make -C doc

$(BUILD):
	mkdir $(BUILD)

clean:
	$(RM) $(call FixPath,$(BUILD)/*)
	make clean -C doc
	rmdir $(BUILD) doc/html